# Dev Database (Supabase Cloud)
spring.datasource.url=jdbc:postgresql://db.bogoidpytiumidcxeuqq.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Ilovemyparents@786
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.flyway.baseline-version=2

# Dev JWT secret
jwt.secret=${JWT_SECRET:dev-secret-key-please-change-this-2026}

# CORS
cors.allowed-origins=http://localhost:3000,http://localhost:5173

logging.level.com.example.hisabkitabbackend=DEBUG


# Logging Flyway

logging.level.org.flywaydb=DEBUG                                                                                                                                                                       
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG
